# Generated by Django 2.0.2 on 2018-05-14 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0002_auto_20180213_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userleavingmessage',
            name='file',
        ),
    ]
