# Generated by Django 2.0.2 on 2018-05-14 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0003_remove_userleavingmessage_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='userleavingmessage',
            name='file',
            field=models.FileField(default=None, help_text='上传的文件', upload_to='message/images/', verbose_name='上传的文件'),
        ),
    ]
