import unittest
from HTMLTestRunner import HTMLTestRunner


def add(a, b):
    return a + b


def minues(a, b):
    return a - b


def multi(a, b):
    return a * b


def divide(a, b):
    return a / b


class TestMathFunc(unittest.TestCase):
    def test_add(self):
        self.assertEqual(3, add(1, 2))
        # self.assertNotEqual(3, add(1, 2))
        self.assertNotEqual(3, add(1, 1))


if __name__ == '__main__':
    suite = unittest.TestSuite()
    suite.addTests(unittest.TestLoader().loadTestsFromTestCase(TestMathFunc))
    with open('HTMLReport.html', 'w', encoding='utf-8') as f:
        print('1111')
        runner = HTMLTestRunner(stream=f,
                                title=u'我的 Test Report1',
                                description=u'generated by HTMLTestRunner.',
                                verbosity=2
                                )
        runner.run(suite)
