# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-16 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qmf_api', '0004_auto_20180716_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlist',
            name='c_time',
            field=models.DateTimeField(blank=True, max_length=255, null=True, verbose_name='时间'),
        ),
    ]
