# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-16 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qmf_api', '0003_auto_20180716_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlist',
            name='order_no',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='订单号'),
        ),
    ]
