# Generated by Django 2.0 on 2018-08-28 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qmf_api', '0006_auto_20180716_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlist',
            name='account_status',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='结算状态'),
        ),
    ]
