# Generated by Django 2.0 on 2018-08-29 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qmf_api', '0007_orderlist_account_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlist',
            name='charge',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='手续费'),
        ),
    ]
