# Generated by Django 2.0 on 2018-08-29 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qmf_api', '0008_orderlist_charge'),
    ]

    operations = [
        migrations.CreateModel(
            name='paymentList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.CharField(blank=True, max_length=255, null=True, verbose_name='时间')),
                ('end_date', models.CharField(blank=True, max_length=255, null=True, verbose_name='时间')),
                ('trade_no', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='订单号')),
                ('withdraw_status', models.CharField(blank=True, max_length=255, null=True, verbose_name='提现状态')),
                ('trade_money', models.CharField(blank=True, max_length=255, null=True, verbose_name='金额')),
                ('charge', models.CharField(blank=True, max_length=255, null=True, verbose_name='金额')),
                ('trade_status', models.CharField(blank=True, max_length=255, null=True, verbose_name='支付状态')),
            ],
            options={
                'verbose_name': '提现详情',
                'verbose_name_plural': '提现详情',
            },
        ),
    ]
