# Generated by Django 2.0 on 2018-08-29 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qmf_api', '0009_paymentlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentlist',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='username'),
        ),
    ]
