# Generated by Django 2.0 on 2018-09-03 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qmf_api', '0010_paymentlist_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlist',
            name='belong',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='归属'),
        ),
    ]
