# Generated by Django 2.0.2 on 2018-06-20 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0005_auto_20180620_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='post_script',
            field=models.CharField(default='', max_length=200, verbose_name='订单留言'),
        ),
    ]
