# Generated by Django 2.0.2 on 2018-05-15 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=22)),
                ('bloodgroup', models.CharField(max_length=22)),
                ('birthmark', models.CharField(max_length=44)),
            ],
        ),
    ]
