# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-24 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_auto_20180522_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='Join_time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=30, null=True, verbose_name='姓名')),
                ('join_time', models.CharField(choices=[('1', '1小时'), ('2', '2小时'), ('3', '3小时'), ('4', '4小时'), ('6', '6小时')], max_length=3, verbose_name='加入时间')),
            ],
        ),
        migrations.AlterField(
            model_name='people',
            name='money',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='金额'),
        ),
        migrations.AlterField(
            model_name='people',
            name='username',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='姓名'),
        ),
    ]
