# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-25 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_auto_20180524_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='join_time',
            name='event_status',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='活动状态'),
        ),
        migrations.AddField(
            model_name='join_time',
            name='prize',
            field=models.IntegerField(blank=True, null=True, verbose_name='奖金'),
        ),
    ]
