# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-25 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0006_auto_20180525_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='join_time',
            name='event_status',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='活动状态'),
        ),
    ]
