# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-25 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0008_auto_20180525_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='join_time',
            name='event_status',
            field=models.IntegerField(blank=True, choices=[('0', '审核中'), ('1', '成功'), ('2', '失败')], default=0, null=True, verbose_name='活动状态'),
        ),
        migrations.AlterField(
            model_name='join_time',
            name='join_time',
            field=models.CharField(choices=[('1', '1小时'), ('2', '2小时'), ('3', '3小时'), ('4', '4小时'), ('6', '6小时')], max_length=3, verbose_name='参与时长'),
        ),
    ]
