# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-25 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0009_auto_20180525_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='join_time',
            name='tixian_status',
            field=models.IntegerField(default=0, verbose_name='提现状态'),
        ),
    ]
