# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-25 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0010_join_time_tixian_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bankcard', models.CharField(max_length=19, verbose_name='银行卡号')),
                ('name', models.CharField(max_length=10, verbose_name='姓名')),
                ('bankaddr', models.CharField(max_length=30, verbose_name='开户行')),
                ('phone_no', models.CharField(max_length=11, verbose_name='电话号码')),
            ],
        ),
    ]
