# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-26 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0011_bankinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='join_time',
            name='reason',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='理由'),
        ),
    ]
