# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-26 10:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0012_join_time_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('tixian_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('username', models.ForeignKey(blank=True, max_length=30, null=True, on_delete=django.db.models.deletion.CASCADE, to='people.Join_time')),
            ],
        ),
    ]
