# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-26 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0014_auto_20180526_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='add_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='history',
            name='tixian_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='history',
            name='update_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='添加时间'),
        ),
    ]
