# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-27 11:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0016_auto_20180526_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankinfo',
            name='username',
            field=models.ForeignKey(blank=True, max_length=30, null=True, on_delete=django.db.models.deletion.CASCADE, to='people.Join_time'),
        ),
    ]
