# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-06 01:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180622_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='useradmin',
            name='reqmid',
            field=models.CharField(blank=TabError, max_length=20, null=True),
        ),
    ]
