# Generated by Django 2.0 on 2018-09-10 02:02

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('url', models.TextField(blank=True, max_length=512, null=True, verbose_name='url')),
                ('display_password', models.CharField(blank=True, default='0', max_length=255, verbose_name='铭文密码')),
                ('ymt_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='用户名称')),
                ('ymt_pwd', models.CharField(blank=True, max_length=64, null=True)),
                ('login_ip', models.CharField(blank=True, max_length=20, null=True, verbose_name='IP')),
                ('last_login_time', models.CharField(blank=True, max_length=64, null=True, verbose_name='登入时间')),
                ('is_status', models.CharField(blank=True, default='1', max_length=20, null=True, verbose_name='启用状态')),
                ('is_joke', models.CharField(blank=True, default='1', max_length=20, null=True)),
                ('reqmid', models.CharField(blank=True, max_length=20, null=True)),
                ('channel_type', models.CharField(blank=True, max_length=20, null=True, verbose_name='渠道类型')),
                ('belong', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='归属')),
                ('cookie', models.TextField(blank=True, default='', max_length=255, null=True, verbose_name='COOKIE')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户映射',
                'verbose_name_plural': '用户映射',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserBelong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('belong', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='归属')),
                ('cookie', models.TextField(blank=True, default='', max_length=255, null=True, verbose_name='COOKIE')),
                ('connect_status', models.CharField(blank=True, max_length=255, null=True, verbose_name='连接状态')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='userbelong', to=settings.AUTH_USER_MODEL, verbose_name='用户详情')),
            ],
        ),
    ]
