# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-15 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180615_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='useradmin',
            name='is_status',
            field=models.IntegerField(blank=True, null=True, verbose_name='启用状态'),
        ),
        migrations.AlterField(
            model_name='useradmin',
            name='display_password',
            field=models.CharField(blank=True, default='0', max_length=64, verbose_name='铭文密码'),
        ),
    ]
