# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-15 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180615_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useradmin',
            name='is_status',
            field=models.CharField(blank=True, default='1', max_length=20, null=True, verbose_name='启用状态'),
        ),
    ]
