# Generated by Django 2.0 on 2018-07-19 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20180713_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='useradmin',
            name='channel_type',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='渠道类型'),
        ),
        migrations.AlterField(
            model_name='useradmin',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='useradmin',
            name='reqmid',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
