# Generated by Django 2.0 on 2018-09-04 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20180719_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='useradmin',
            name='belong',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='渠道类型'),
        ),
    ]
