# Generated by Django 2.0 on 2018-09-04 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_useradmin_belong'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useradmin',
            name='belong',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='渠道类型'),
        ),
    ]
